- name: Copy MongoDB Yum Repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB Server
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Update MongoDB Listen Address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongoDB
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes

#- name: Copy Mongo repo
#  ansible.builtin.copy:
#    src: mongo.repo
#    dest: /etc/yum.repos.d/mongo.repo
#
#- name: Install Mongodb
#  ansible.builtin.yum:
#    name: mongodb-org
#    state: installed
#
#- name: Start service
#  ansible.builtin.service:
#    name: mongod
#    state: started
#
#- name: Changing Port
#  ansible.builtin.replace:
#    path: /etc/mongod.conf
#    regexp: '127.0.0.1'
#    replace: '0.0.0.0'
#
#- name: Restart service
#  ansible.builtin.service:
#    name: mongod
#    state: restarted