- name: Creating Parameters
  hosts: localhost
  connection: local
  tasks:
    - name: Create or update key/value pair in AWS SSM parameter store
      community.aws.ssm_parameter:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        region: "us-east-1"

      loop:
        - {name: "dev.cart.REDIS_HOST", value: "redis-dev.ramdevops35.online"}
        - {name: "dev.cart.CATALOGUE_HOST", value: "catalogue-dev.ramdevops35.online"}
        - {name: "dev.catalogue.MONGO", value: "true"}
        - {name: "dev.catalogue.MONGO_URL", value: "mongodb://mongodb-dev.ramdevops35.online:27017/catalogue"}
        - {name: "dev.frontend.CATALOGUE_URL", value: "proxy_pass http://catalogue-dev.ramdevops35.online:8080/"}
        - {name: "dev.frontend.USER_URL", value: "proxy_pass http://user-dev.ramdevops35.online:8080/"}
        - {name: "dev.frontend.CART_URL", value: "proxy_pass http://cart-dev.ramdevops35.online:8080/"}
        - {name: "dev.frontend.SHIPPING_URL", value: "proxy_pass http://shipping-dev.ramdevops35.online:8080/"}
        - {name: "dev.frontend.PAYMENT_URL", value: "proxy_pass http://payment-dev.ramdevops35.online:8080/"}
        - {name: "dev.shipping.CART_ENDPOINT", value: "cart-dev.ramdevops35.online:8080/"}
        - {name: "dev.shipping.DB_HOST", value: "mysql-dev.ramdevops35.online"}
        - {name: "dev.user.MONGO", value: "true"}
        - {name: "dev.user.REDIS_HOST", value: "redis-dev.ramdevops35.online"}
        - {name: "dev.user.MONGO_URL", value: "mongodb://mongodb-dev.ramdevops35.online:27017/users"}

    - name: Secrets
      community.aws.ssm_parameter:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        region: "us-east-1"
        string_type: "SecureString"
      loop:
        - { name: "dev.payment.AMPQ_PASS", value: "Roboshop@1" }
