- name: Creating Parameters
  hosts: localhost
  connection: local
  tasks:
    - name: Create or update key/value pair in AWS SSM parameter store
      community.aws.ssm_parameter:
        name: "Hello"
        value: "World"
        region: "us-east-1"