- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Start service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Removing Nginx Default content
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Create a directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: Download and Extracting
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy Roboshop conf
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start service
  ansible.builtin.service:
    name: nginx
    state: restarted


