- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Start service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Removing Nginx Default content
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Create a directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: Download and Extracting
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes




#source common.sh
#
#print_head "Installing Nginx"
#yum install nginx -y &>>${LOG}
#status_check
#
#print_head "Starting Service"
#systemctl enable nginx &>>${LOG}
#systemctl start nginx &>>${LOG}
#status_check
#
#
#rm -rf /usr/share/nginx/html/* &>>${LOG}
#
#print_head "Downloading web content"
#curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip &>>${LOG}
#status_check
#
#print_head "Extracting web content"
#cd /usr/share/nginx/html &>>${LOG}
#unzip /tmp/frontend.zip &>>${LOG}
#status_check
#
#print_head "Configuring Reverse Proxy"
#cp ${script_location}/files/nginx-roboshop.conf /etc/nginx/default.d/roboshop.conf &>>${LOG}
#status_check