- name: Disable Repo
  ansible.builtin.shell: yum module disable mysql -y

- name: Copy Repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install Mysql
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: Start Service
  ansible.builtin.systemd:
    name: mysqld
    enabled: yes
    state: restarted

- name: Setting up Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{mysql_password}}
