- name: Install NodeJS
  ansible.builtin.yum:
    name: maven
    state: installed

- name: AppPreReq
  ansible.builtin.include_tasks: app-prereq.yml

- name: MVN build
  ansible.builtin.shell: mvn clean package
  args:
    chdir: /app

- name: Systemd setup
  ansible.builtin.include_tasks: systemd.yml

- name: Schema Load
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load