- name: COpy SystemD file
  ansible.builtin.copy:
    src: "{{component}}.conf"
    dest: /etc/systemd/system/{{component}}.service

- name: Start {{component}} Service
  ansible.builtin.systemd:
    name: "{{component}}"
    daemon_reload: yes
    enabled: yes
    state: restarted